language: node_js
node_js:
  - "8"
  - "9"

addons:
  mariadb: '10.2'

cache: yarn

install: yarn
script:
  - yarn lint
  # we use `--runInBand` because different tests create/delete the database at
  # the same time..
  - yarn test --runInBand --forceExit

jobs:
  include:
    - stage: npm release
      node_js: "8"
      script: yarn compile
      before_deploy:
        - cd dist
      deploy:
        provider: npm
        email: "$NPM_EMAIL"
        api_key: "$NPM_TOKEN"
        skip_cleanup: true
        on:
          tags: true
